version: "3.7"

services:

  api:
    build: .
    image: topic-tool/api:latest
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=27017
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}

  db:
    image: mongo:bionic
    command: mongod --replSet rs --bind_ip_all
    volumes:
      - db-data:/data/db

  db_init:
    image: mongo:bionic
    # Set up single node replica set to enable support for transactions
    command: sleep 30 && echo "rs.initiate({_id:'rs',members:[{_id:0,host:\"db:27017\"}]})" | mongo --host db:27017
    depends_on:
      - db

volumes:
  db-data:
