version: "3.7"

services:

  api:
    build: .
    image: topic-tool/api:latest
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=27017
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}

  db:
    image: mongo:bionic
    volumes:
      - db-data:/data/db

volumes:
  db-data:
